// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"gpio", '{
        '{32'h40000000, 32'h4000ffff}
    }},
    '{"clkmgr", '{
        '{32'h40020000, 32'h4002ffff}
    }},
    '{"rstmgr", '{
        '{32'h40030000, 32'h4003ffff}
    }},
    '{"pwrmgr", '{
        '{32'h40040000, 32'h4004ffff}
    }},
    '{"uart", '{
        '{32'h41000000, 32'h4100ffff}
    }},
    '{"i2c", '{
        '{32'h42000000, 32'h4200ffff}
    }},
    '{"spi_device", '{
        '{32'h43000000, 32'h4300ffff}
    }},
    '{"timer", '{
        '{32'h44000000, 32'h4400ffff}
    }},
    '{"spi_host", '{
        '{32'h45000000, 32'h4500ffff}
    }},
    '{"plic", '{
        '{32'h48000000, 32'h4bffffff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"axi_xbar", 0, '{
        "gpio",
        "clkmgr",
        "rstmgr",
        "pwrmgr",
        "uart",
        "i2c",
        "spi_device",
        "timer",
        "spi_host",
        "plic"}}
};
